### ISSUE TITLE
Better comments are different

### ISSUE THREAD

**Issue by jletey** [mtdmali/daybreak-theme#1]
Let me start out by saying thank you so much for creating this theme @mtdmali! Been really enjoying it!

In your readme, you give code for the Better Comment extension, which I copied-pasted into my settings:

![Shot 2019-07-28 at 09 00 12](https://user-images.githubusercontent.com/30328854/62003913-2afaff00-b116-11e9-9e79-b11695784b4f.jpg)

but for some reason, the comments aren't showing up correctly:

![Shot 2019-07-28 at 09 00 22](https://user-images.githubusercontent.com/30328854/62003915-2f271c80-b116-11e9-9912-ea72223ae40d.jpg)

Note that I'm using the Better Comments version 2.0.5 (the latest)

P.S. (completely unrelated) I really like the way your terminal looks in the screenshot, do you mind sharing what terminal/shell you're using and your prompt configuration?

**Comment by mtdmali** [comment]
@johnletey Thanks for the kind words, I'm really happy you've been enjoying it thus far!

I noticed your initial screenshot had the incorrect settings, but it seems to me that your updated screenshot shows the right settings. Are they working now? Please let me know.

I'll paste my settings again here for reference:

```json
"better-comments.tags": [
    {
      "tag": "!",
      "color": "#2E302E",
      "strikethrough": false,
      "backgroundColor": "#E95678"
    },
    {
      "tag": "?",
      "color": "#2E302E",
      "strikethrough": false,
      "backgroundColor": "#B877DB"
    },
    {
      "tag": "//",
      "color": "#474747",
      "strikethrough": true,
      "backgroundColor": "transparent"
    },
    {
      "tag": "todo",
      "color": "#FAB795",
      "strikethrough": false,
      "backgroundColor": "#2E302E"
    },
    {
      "tag": "*",
      "color": "#FDF0ED",
      "strikethrough": false,
      "backgroundColor": "transparent"
    },
    {
      "tag": "#",
      "color": "#FDF0ED",
      "strikethrough": false,
      "backgroundColor": "#2E302E"
    },
    {
      "tag": "_",
      "color": "#2E302E",
      "strikethrough": false,
      "backgroundColor": "#FDF0ED"
    }
  ],
```
As for the integrated terminal appearance in VS Code, all you need to do is update your bash PS1 appearance. For MacOS users:

* Open Terminal
* Open preferences with `⌘,`
* Select `Shell opens with: Command (complete path): /bin/bash`
* Then, in Terminal, enter `nano ~/.bash_profile`
* There might be some stuff in here / it might be empty, but you'll want to paste your PS1 settings into this file. Use your arrow keys to navigate, and you can type/paste like any other text editor.
* My PS1 settings are `export PS1="\[$(tput bold)\]\[\033[38;5;0m\]\[\033[48;5;15m\]\u\[$(tput sgr0)\]\[$(tput sgr0)\]\[\033[38;5;15m\]\[\033[48;5;-1m\] \[$(tput bold)\]\[$(tput sgr0)\]\[\033[38;5;11m\][\w]:\[$(tput sgr0)\]\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]"`
* After you've pasted your settings, press `⌃o` followed by the enter key to save the file.
* Press `⌃x` to exit.
* Re-open Terminal to see the changes.

> **Note:** the colors might look ugly in your standard Terminal app, but it will look correct in your VS Code integrated terminal. I never use Terminal so it's not an issue for me. I highly recommend [**Hyper**](https://hyper.is/) if you need to use a standalone CLI.

If you wanted to customize your own PS1 appearance, I recommend http://bashrcgenerator.com/. It will generate your settings, but just ensure you paste it in `nano ~/.bash_profile` as opposed to `nano ~/.bashrc` as they instruct in their docs.

Let me know if that works / is understandable, I may add these instructions to the README.

**Comment by jletey** [comment]
> Are they working now? Please let me know.

@mtdmali Yes ... the code that you just included works as expected!

> All you need to do is update your bash PS1 appearance

Thank you ... I use Zsh right now, so I'll see what I can do to transfer the above given instructions over to Zsh! I'll keep you posted!

**Comment by jletey** [comment]
@mtdmali The terminal looks amazing! (Just tested in Bash) Will need to spend some time to transfer over to Zsh though ... I'll keep you posted!

**Comment by mtdmali** [comment]
I'm gonna close this for now, we should open a new issue for the bash appearance settings.
