### ISSUE TITLE
Status bar is off color

### ISSUE THREAD

**Issue by mittalyashu** [mtdmali/daybreak-theme#3]
The color of the status bar doesn't match with the whole theme.

![image](https://user-images.githubusercontent.com/29014463/62103391-fd4ebb00-b2b9-11e9-9379-f34af2b753d7.png)

**Comment by mittalyashu** [comment]
| |
| --- |
| ![image](https://user-images.githubusercontent.com/29014463/62103613-8fef5a00-b2ba-11e9-939f-5708ebcd5c8e.png) |
| ![image](https://user-images.githubusercontent.com/29014463/62103621-954ca480-b2ba-11e9-8981-452c4afa6a52.png) |
| ![image](https://user-images.githubusercontent.com/29014463/62103632-9bdb1c00-b2ba-11e9-838a-a301af96ec10.png) |
| ![image](https://user-images.githubusercontent.com/29014463/62103664-b01f1900-b2ba-11e9-9fd4-eccf374a260e.png) |

**Comment by mtdmali** [comment]
@mittalyashu Could you elaborate more on this issue and/or provide an alternative? I believe it looks fine as is.

**Comment by mittalyashu** [comment]
I think this color should be used on more highlightable things.

For example: If we have a focus on a specific line of code, or hover on the specific extension.

**Comment by mtdmali** [comment]
@mittalyashu I'm still unsure of what you're suggesting.
