### ISSUE TITLE
Icon color same as count badge

### ISSUE THREAD

**Issue by mittalyashu** [mtdmali/daybreak-theme#4]
The color of the icon in the sidebar is same as count badge.

![image](https://user-images.githubusercontent.com/29014463/62103472-2ec78680-b2ba-11e9-86a0-442907471073.png)

**Comment by mtdmali** [comment]
@mittalyashu  AFAIK there is no way to alter the `activityBarBadge.background` when the activity bar icon is active.

It was intended that the activity bar badge be consistent with the primary theme color, as shown:

<img width="56" alt="Screen Shot 2019-07-30 at 10 24 09 AM" src="https://user-images.githubusercontent.com/35084740/62137590-371cc300-b2b4-11e9-9ea4-bd115b75432b.png">

The other alternative would be white? That doesn't look nearly as good IMO:

<img width="62" alt="Screen Shot 2019-07-30 at 10 37 05 AM" src="https://user-images.githubusercontent.com/35084740/62138669-ffaf1600-b2b5-11e9-89c5-18539edcaf8b.png">

If you have any suggestions on what the color should be, feel free to suggest an alternative.

**Comment by mittalyashu** [comment]
Here's another example:

![image](https://user-images.githubusercontent.com/29014463/62277051-ffa04900-b462-11e9-94d9-bae39227e088.png)

**Comment by mtdmali** [comment]
@mittalyashu Are you suggesting we make the activity bar badge blue? Or are you suggesting you would like them to be different colors?

If you're suggesting them to be different colors, which colors would you suggest?
