### ISSUE TITLE
iTerm version

### ISSUE THREAD

**Issue by tdeekens** [mtdmali/daybreak-theme#7]
This theme is so nice. Did you plan to roll out out to iTerm too or is there a way to convert it?

**Comment by jletey** [comment]
I was also thinking of an iTerm theme and also a vim theme as well!

**Comment by tdeekens** [comment]
Oh that would be so sweet.

**Comment by mtdmali** [comment]
@tdeekens @johnletey I use Hyper (https://hyper.is/) if not working directly in VS Code.

I can look into iTerm and Vim, although admittedly I am terrified of the latter...

**Comment by tdeekens** [comment]
iTerm would be more than enough for me. The Vim mode in VSCode is decent enough and works nicely with the theme.
